const express = require('express');
const router = express.Router();
const docs = require('./docs');
const users = require('./users');
const candles = require('./candles');
const wallets = require('./wallets');
const exchanges = require('./exchanges');
const intervals = require('./intervals');
const instruments = require('./instruments');
const order_types = require('./order_types');
const strategies = require('./strategies');
const managed_strategies = require('./managed_strategies');
const activity = require('./activity');
const status = require('./status');
const pairs = require('./pairs');
const equity = require('./equity');
const bitmex = require('./bitmex/index');
const kraken = require('./kraken/index');
const auth = require('./auth');

router.use('/docs', docs);
router.use('/auth', auth);
router.use('/equity', equity);
router.use('/strategies', strategies);
router.use('/candles', candles);
router.use('/users', users);
router.use('/bitmex', bitmex);
router.use('/kraken', kraken);
router.use('/wallets', wallets);
router.use('/exchanges', exchanges);
router.use('/intervals', intervals);
router.use('/managed-strategies', managed_strategies);
router.use('/order-types', order_types);
router.use('/instruments', instruments);
router.use('/activity', activity);
router.use('/status', status);
router.use('/pairs', pairs);

module.exports = router;
